# render.yaml

# 1. A managed Postgres instance
databases:
  - name: insight-postgres
    plan: free

services:
  # 2. A managed Redis key/value store
  - type: keyvalue
    name: insight-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all

  # 3. Node.js backend
  - type: web
    name: insight-backend
    runtime: node
    plan: free
    region: oregon
    repo: https://github.com/AntonioCoppe/311-insight-dashboard.git
    branch: main
    buildCommand: |
      cd src/backend
      npm install
    startCommand: |
      cd src/backend
      node app.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: insight-postgres
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: insight-redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: insight-redis
          property: port
      - key: PORT
        value: "3000"

  # 4. React frontend (static site)
  - type: web
    name: insight-frontend
    runtime: static
    plan: free
    repo: https://github.com/AntonioCoppe/311-insight-dashboard.git
    branch: main
    buildCommand: |
      cd src/frontend
      npm install
      npm run build
    staticPublishPath: src/frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://insight-backend.onrender.com/api"
